server:
  port: 4444

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认根据serviceId大写路由
          lower-case-service-id: true #根据serviceId小写路由

eureka:
  client:
    service-url:
      defaultZone:  http://smallsand:smallsand@service1:7777/eureka/,http://smallsand:smallsand@service2:8888/eureka/,http://smallsand:smallsand@service3:9999/eureka/
