server:
  port: 7777
spring:
  application:
    name: eureka-service
  security:
    user:
      name: smallsand
      password: smallsand
eureka:
  instance:
    hostname: service1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  http://smallsand:smallsand@service2:8888/eureka/,http://smallsand:smallsand@service3:9999/eureka/

