spring:
  application:
    name: cloud-user
server:
  port: 4001

eureka:
  client:
    service-url:
      defaultZone:  http://smallsand:smallsand@service1:7777/eureka/,http://smallsand:smallsand@service2:8888/eureka/,http://smallsand:smallsand@service3:9999/eureka/

logging:
  level:
    com:
      qxxg:
        springcloud: debug