spring:
  application:
    name: cloud-user
server:
  port: 4001

eureka:
  client:
    service-url:
      defaultZone:  http://smallsand:smallsand@service1:7777/eureka/

logging:
  level:
    com:
      qxxg:
        springcloud: debug
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

